### ISSUE TITLE
combine two protobuf 3.0's defs, only one {proto3_msgs, [...]} works, other sill packed like protobuf 2.0, preset default value in binary. 

### ISSUE THREAD

**Issue by dogtapdsd** [jinganix/enif_protobuf#27]
> %% message with gpb 4.18.0
%% -- test_proto3_default02.proto
%% protobuf v3 
%% syntax = "proto3";
%% message default_uint32_msg {
%%    uint32 count_num = 1; 
%% }
%%
%% -- test_proto3_default02.proto
%% syntax = "proto3";
%% message default_string_mix_msg {
%%     uint32 count_num = 1; 
%%     string rname    = 2;
%%     uint32 py_id   = 3; 
%%     uint32 py_num   = 4; 
%% }
-module(test_protobuf_encode).
-export([
        combine_two_defs/0
    ]).
-include_lib("gpb.hrl").
-record(default_uint32_msg,
        {count_num = 0          :: non_neg_integer() | undefined % = 1, optional, 32 bits
        }).
-record(default_string_mix_msg,
        {count_num = 0          :: non_neg_integer() | undefined, % = 1, optional, 32 bits
         rname = []             :: unicode:chardata() | undefined, % = 2, optional
         py_id = 0              :: non_neg_integer() | undefined, % = 3, optional, 32 bits
         status_arr = []        :: [non_neg_integer()] | undefined, % = 4, repeated, 32 bits
         py_num = 0             :: non_neg_integer() | undefined, % = 5, optional, 32 bits
         gname = []             :: unicode:chardata() | undefined, % = 6, optional
         gnum = 0               :: non_neg_integer() | undefined % = 7, optional, 32 bits
        }).
get_proto_defs() ->
    [%{proto_defs_version, 1},
     %{file, {"test_proto3_default", "test_proto3_default.proto"}},
     %{{msg_containment, "test_proto3_default"}, [default_uint32_msg]},
     %{{enum_containment, "test_proto3_default"}, []},
     {syntax, "proto3"},
     {{msg, default_uint32_msg}, [#field{name = count_num, fnum = 1, rnum = 2, type = uint32, occurrence = optional, opts = []}]},
     {proto3_msgs, [default_uint32_msg]}].
get_proto_defs_02() ->
    [%{proto_defs_version, 1},
     %{file, {"test_proto3_default02", "test_proto3_default02.proto"}},
     %{{msg_containment, "test_proto3_default02"}, [default_string_mix_msg]},
     %{{enum_containment, "test_proto3_default02"}, []},
     {syntax, "proto3"},
     {{msg, default_string_mix_msg},
      [#field{name = count_num, fnum = 1, rnum = 2, type = uint32, occurrence = optional, opts = []},
       #field{name = rname, fnum = 2, rnum = 3, type = string, occurrence = optional, opts = []},
       #field{name = py_id, fnum = 3, rnum = 4, type = uint32, occurrence = optional, opts = []},
       #field{name = status_arr, fnum = 4, rnum = 5, type = uint32, occurrence = repeated, opts = [packed]},
       #field{name = py_num, fnum = 5, rnum = 6, type = uint32, occurrence = optional, opts = []},
       #field{name = gname, fnum = 11, rnum = 7, type = string, occurrence = optional, opts = []},
       #field{name = gnum, fnum = 12, rnum = 8, type = uint32, occurrence = optional, opts = []}]},
     {proto3_msgs, [default_string_mix_msg]}].
%% @doc 
combine_two_defs() -> 
    io:format("diff combine_two_defs...~n",[]),
    enif_protobuf:load_cache(get_proto_defs_02() ++ get_proto_defs()),
    %% proto3 default value not be serialized ok
    Defaultuint32 = #default_uint32_msg{},
    EnifPacked = enif_protobuf:encode(Defaultuint32),
    GpbPacked = test_proto3_default:encode_msg(Defaultuint32),
    io:format("default value not packed ...~n",[]),
    io:format("enif_protobuf:encode/1 packed, byte_size:~w, binary:~w ~n", [erlang:byte_size(EnifPacked), EnifPacked]),
    io:format("test_proto3_default:encode_msg/1 packed, byte_size:~w, binary:~w ~n", [erlang:byte_size(GpbPacked), GpbPacked]),
    %% proto3 default value was present in the binary
    DataRd = #default_string_mix_msg{count_num = 99, rname = <<"test">>, py_id = 0, status_arr = [],  gname = <<>>},
    EnifPacked02 = enif_protobuf:encode(DataRd),
    GpbPacked02 = test_proto3_default02:encode_msg(DataRd),
    io:format("default value packed ...~n",[]),
    io:format("enif_protobuf:encode/1 packed, byte_size:~w, binary:~w ~n", [erlang:byte_size(EnifPacked02), EnifPacked02]),
    io:format("test_proto3_default02:encode_msg/1 packed, byte_size:~w, binary:~w ~n", [erlang:byte_size(GpbPacked02), GpbPacked02]),
    ok.

a reproduce code like this

**Comment by jg513** [comment]
fixed, please refer to [ep_issue_27_tests](https://github.com/jg513/enif_protobuf/blob/master/test/ep_issue_27_tests.erl)
