### ISSUE TITLE
make failed on OTP 25 project

### ISSUE THREAD

**Issue by bighunter513** [jinganix/enif_protobuf#34]
=ERROR REPORT==== 17-Jun-2022::19:06:09.059862 ===
beam/beam_load.c(148): Error loading module enc:
  please re-compile this module with an Erlang/OTP 25 compiler

escript: exception error: undefined function enc:main/1
  in function  escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
===> Hook for compile failed!

**Comment by dong50252409** [comment]
OPT 26 has the same problem
